newrelic:
  labels: null 

ingress_external:
  host: manifest_not_included_in_this_profile

ingress_restricted:
  host: use1-prod-python-project-test.percipio.com

virtualservice_restricted:
  host: use1-prod-python-project-test.percipio.com